apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-data-pv
  labels:
    type: local
    app: forgejo
spec:
  storageClassName: forgejo-local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/lib/forgejo-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - binning.net
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data-pvc
  namespace: forgejo
  labels:
    app: forgejo
spec:
  storageClassName: forgejo-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
