apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
  namespace: forgejo
  labels:
    app: forgejo
data:
  USER_UID: "1000"
  USER_GID: "1000"
  FORGEJO__service__DISABLE_REGISTRATION: "true"
  FORGEJO__database__DB_TYPE: "postgres"
  FORGEJO__database__HOST: "postgres-svc"
  FORGEJO__database__PORT: "5432"
  FORGEJO__database__NAME: "forgejo"
  FORGEJO__database__SSL_MODE: "disable"
  FORGEJO__server__ROOT_URL: "https://forgejo.binning.dev/"
  FORGEJO__server__DOMAIN: "forgejo.binning.dev"
